# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - axis_1
    - axis_2
    - axis_3
    - axis_4
    - axis_5
    - axis_6
    - axis_parmak_1
    - axis_parmak_2
  sim_control_mode: 1  # 0: position, 1: velocity
controller_list:
  []

rover_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - axis_1
    - axis_2
    - axis_3
    - axis_4
    - axis_5
    - axis_6
  # gains:
  #     axis_1: {p: 10000, i: 1, d: 1000}
  #     axis_2: {p: 10000, i: 1, d: 1000}
  #     axis_3: {p: 10000, i: 1, d: 1000}
  #     axis_4: {p: 10000, i: 1, d: 1000}
  #     axis_5: {p: 10000, i: 1, d: 1000}
  #     axis_6: {p: 10000, i: 1, d: 1000}

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10


rover_arm_right_finger:
    type: position_controllers/JointPositionController
    joint: axis_parmak_1


rover_arm_left_finger:
    type: position_controllers/JointPositionController
    joint: axis_parmak_2
