# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: manipulator
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - axis1
    - axis2
    - axis3
    - axis4
    - axis5
    - axis6
    - axisparmak1
    - axisparmak2
  sim_control_mode: 1  # 0: position, 1: velocity
controller_list:
  []

rover_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - axis1
    - axis2
    - axis3
    - axis4
    - axis5
    - axis6

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10


rover_arm_right_finger:
    type: position_controllers/JointPositionController
    joint: axisparmak1


rover_arm_left_finger:
    type: position_controllers/JointPositionController
    joint: axisparmak2
