gazebo_ros_control/pid_gains: # Gazebo pid paramters for 21 robot arm.
  joint_1: {p: 10000.0, i: 0.03, d: 2.0}
  joint_2: {p: 2500.0, i: 0.02, d: 50.0}
  joint_3: {p: 30000.0, i: 0.01, d: 2.0}
  joint_4: {p: 1500.0, i: 0.01, d: 10.0}
  joint_5: {p: 1000.0, i: 0.02, d: 1.0}
