#fourth_robot:
rover_joint_publisher:
  type: joint_state_controller/JointStateController
  publish_rate: 50

#Controller for Teleopretion if you want these controllers please uncomment this below
four_wheel_steering_controller:
  type        : "four_wheel_steering_controller/FourWheelSteeringController"
  front_wheel: ['wheel_leftfront_joint','wheel_rightfront_joint']
  rear_wheel: ['wheel_leftrear_joint', 'wheel_rightrear_joint']
  front_steering: ['steering_leftfront_joint','steering_rightfront_joint']
  rear_steering: ['steering_leftrear_joint', 'steering_rightrear_joint']
  publish_rate: 50.0
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  cmd_vel_timeout: 25.0 # not tested here

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.122
  wheel_radius : 0.026
  wheel_steering_y_offset : 0.03

    # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier    : 1.0

    # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 1.0
    
    # Base frame_id
  base_frame_id: base_link #default: base_link

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.5   # m/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0   # rad/s^2

# rover_steering_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - steering_leftfront_joint
#     - steering_rightfront_joint
#     - steering_leftrear_joint
#     - steering_rightrear_joint

# rover_wheel_leftfront:
#   type: velocity_controllers/JointVelocityController
#   joint: wheel_leftfront_joint

# rover_wheel_rightfront:
#   type: velocity_controllers/JointVelocityController
#   joint: wheel_rightfront_joint

# rover_wheel_leftrear:
#   type: velocity_controllers/JointVelocityController
#   joint: wheel_leftrear_joint

# rover_wheel_rightrear:
#   type: velocity_controllers/JointVelocityController
#   joint: wheel_rightrear_joint
